export const measurementsData = [
  {
    id: '1',
    date: '3/10/23',
    weight: '135',
    bodyFatPercent: '18',
    chin: '7',
    cheek: '6',
    pec: '4',
    bicep: '6',
    tricep: '12',
    subscap: '14',
    australian: '17', 
    auxiliary: '7',
    suprailiac: '8',
    umbilicus: '14',
    knee: '7',
    calf: '8',
    quad: '17',
    hamstring: '17'
  }, 
  {
    id: '2',
    date: '4/12/2023',
    weight: '130',
    bodyFatPercent: '16',
    chin: '6',
    cheek: '5',
    pec: '3.5',
    bicep: '5.5',
    tricep: '11',
    subscap: '12',
    australian: '14', 
    auxiliary: '6',
    suprailiac: '6',
    umbilicus: '12',
    knee: '6',
    calf: '7',
    quad: '15.5',
    hamstring: '15.5'
  }, 
  {
    id: '3',
    date: '5/12/2023',
    weight: '128',
    bodyFatPercent: '15.5',
    chin: '5',
    cheek: '5',
    pec: '3',
    bicep: '5',
    tricep: '10',
    subscap: '10.5',
    australian: '12', 
    auxiliary: '5.5',
    suprailiac: '5',
    umbilicus: '10',
    knee: '6',
    calf: '7',
    quad: '15',
    hamstring: '15'
  }
]
